- name: install MariaDB (Ubuntu)
  tags: ubuntu,mariadb
  apt:
    name: mariadb-server
    state: latest
  when: ansible_distribution == "Debian"
 
- name: install MariaDB (CentOS)
  tags: centos,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "CentOS"

