- name: install apache and php
  tags: debian,apache,php
  apt:
    name:
      - apache2
      - libapache2-mod-php       
    state: latest
  when: ansible_distribution == "Debian"
  
- name: install apache and php
  tags: centos,apache,php
  dnf:
    name:
      - httpd
      - php
    state: latest
  when: ansible_distribution == "CentOS"
  
- name: copy html file for the site
  tags: debian,centos,apache,php
  copy:
    src: files/standard.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
 
 
- name: install unzip
  package:
    name: unzip

- name: unarchive test local file
  tags: debian,centos,archive
  unarchive:
    src: files/prerer.zip
    dest: /home
    mode: '0755'
    owner: root
    group: root
    remote_src: false
  
- name: Start apache2 service
  tags: debian,apache
  service:
    name: apache2
    state: started
    enabled: true
  when: ansible_distribution == "Debian"
  
- name: Start httpd service
  tags: centos,httpd
  service:
    name: httpd
    state: started
    enabled: true
  when: ansible_distribution == "CentOS"
 
- name: Ensure the default Apache port is 8080
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen 80
  when: ansible_distribution == "Debian"
  register: apache2

- name: Restart apache2 service
  tags: debian,apache
  service:
    name: apache2
    state: restarted
  when: apache2.changed

