- name: install apache and php
  tags: apache,php
  package:
    name:
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"       
    state: latest
  
- name: copy html file for the site
  tags: debian,centos,apache,php
  copy:
    src: files/standard.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
 
 
- name: install unzip
  package:
    name: unzip

- name: unarchive test local file
  tags: debian,centos,archive
  unarchive:
    src: files/prerer.zip
    dest: /home
    mode: '0755'
    owner: root
    group: root
    remote_src: false
  
- name: Start apache service
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: true
 
- name: Ensure the default Apache port is 8080
  lineinfile:
    path: /etc/apache2/ports.conf
    regexp: '^Listen '
    insertafter: '^#Listen '
    line: Listen 80
  notify: restart_apache 

- name: Restart apache service
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: restarted
 

