---

- hosts: all
  become: true
  pre_tasks:

    - name: install updates (Ubuntu)
      apt:
        upgrade: dist
        update_cache: yes
      when: ansible_distribution == "Debian"

    - name: install updates (CentOS)
      dnf:
        update_only: yes
        update_cache: yes
      when: ansible_distribution == "CentOS"

- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php
    tags: debian,apache,php
    apt: 
      name: 
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Debian"

  - name: install apache and php
    tags: centos,apache,php
    dnf:
      name: 
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
  
  - name: copy html file for the site
    tags: debian,centos,apache,php
    copy:
      src: files/standard.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: '0644'


  - name: install unzip
    package:
      name: unzip

  - name: unarchive test local file
    tags: debian,centos,archive
    unarchive: 
      src: files/prerer.zip
      dest: /home
      mode: '0755'
      owner: root
      group: root 
      remote_src: false  

- hosts: db_servers
  become: true
  tasks:

    - name: install MariaDB (Ubuntu)
      tags: ubuntu,mariadb
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Debian"

    - name: install MariaDB (CentOS)
      tags: centos,mariadb
      dnf: 
        name: mariadb
        state: latest
      when: ansible_distribution == "CentOS"


        
