---

- hosts: all
  become: true
  pre_tasks:

    - name: update repo cache (Debian)
      apt:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "Debian"

    - name: update repo cache (CentOS)
      dnf:
        update_cache: yes
      changed_when: false
      when: ansible_distribution == "CentOS"

- hosts: all
  become: true
  roles:
    - base
        
- hosts: web_servers
  become: true
  roles:
    - web_servers 

- hosts: db_servers
  become: true
  roles:
    - db_servers

        
