---
# Secret (base64)

# - generic -  пароли/токены для приложений
# - docker-registry - данные авторизации в docker registry
# - tls - TLS сертификаты для Ingress

# kubectl create secret generic test --from-literal=test1=asdf --from-literal=dbpassword=1q2w3e
# kubectl get secret

# configMapRef - позволяет брать значение переменной из secret
# через envFrom можно подключить secret целиком

apiVersion: app/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.12
        name: nginx
        envFrom:
        - configMapRef:
            name: my-configmap-env
        env:
        - name: TEST
          value: foo
        - name: TEST_1
          valueFrom:
            secretKeyRef:
              name: test
              key: test1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m

...