---
# Удалить всt типы ресурсов на всех неймспейсах со всеми именами
# kubectl delete all -A --all

# флаг "-n" - в конкретном неймспейсе

# 1 CPU - 1000 mili CPU

# QoS Class:
#  - Guaranteed - столько ресурсов, сколько запросил
#  - Burstable - когда  requests < limits (испольуется 100m, а можно разогнать до 200m)
#  - Best effort - нет лимитов на ресурсы в приложениях, но, в случае нехватки ресурсов,
# с таких в первую очередь будут браться ресурсы


apiVersion: app/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - image: nginx:1.12
        name: nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
...